### ISSUE TITLE
加入差分隐私时self.call_dlg(i)报错

### ISSUE THREAD

**Issue by PaiStardian** [TsingZ0/PFL-Non-IID#128]
作者你好，我在FedAvg算法中使用FMnist数据集进行实验中 使用差分隐私参数
    parser.add_argument('-dp', "--privacy", type=bool, default=True,
                        help="differential privacy")
    parser.add_argument('-dps', "--dp_sigma", type=float, default=2)
    parser.add_argument('-dlg', "--dlg_eval", type=bool, default=True)
    parser.add_argument('-dlgg', "--dlg_gap", type=int, default=5)
时在self.call_dlg(i)中报错Traceback (most recent call last):
  File "E:\yanjiusheng\anaconda\envs\fl\lib\site-packages\torch\optim\optimizer.py", line 140, in wrapper
    out = func(*args, **kwargs)
  File "E:\yanjiusheng\anaconda\envs\fl\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "E:\yanjiusheng\anaconda\envs\fl\lib\site-packages\torch\optim\lbfgs.py", line 312, in step
    orig_loss = closure()
  File "E:\yanjiusheng\anaconda\envs\fl\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\·高\Desktop\PFL-Non-IID-master\system\utils\dlg.py", line 37, in closure
    dummy_grad = torch.autograd.grad(dummy_loss, net.parameters(), create_graph=True)
  File "E:\yanjiusheng\anaconda\envs\fl\lib\site-packages\torch\autograd\__init__.py", line 300, in grad
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "E:\yanjiusheng\anaconda\envs\fl\lib\site-packages\torch\nn\modules\module.py", line 62, in __call__
    return self.hook(module, *args, **kwargs)
  File "E:\yanjiusheng\anaconda\envs\fl\lib\site-packages\opacus\grad_sample\grad_sample_module.py", line 326, in capture_backprops_hook
    activations, backprops = self.rearrange_grad_samples(
  File "E:\yanjiusheng\anaconda\envs\fl\lib\site-packages\opacus\grad_sample\grad_sample_module.py", line 388, in rearrange_grad_samples
    activations = module.activations.pop()
IndexError: pop from empty list
报栈空 我不知道是什么原因 ，作者看到了可以回复我一下 谢谢了

**Comment by TsingZ0** [comment]
分别使用DP和DLG正常，但同时开启DP和DLG是有这个问题，我已经修改了`clientavg.py`代码，现在可以支持同时开启了。感谢！

**Comment by PaiStardian** [comment]
感谢，我直接去git上去拉就可以了吧



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Tsing ***@***.***&gt;
发送时间: 2023年10月13日 15:19
收件人: TsingZ0/PFL-Non-IID ***@***.***&gt;
抄送: PaiStardian ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [TsingZ0/PFL-Non-IID] 加入差分隐私时self.call_dlg(i)报错 (Issue #128)
