### ISSUE TITLE
Fedkd加入差分隐私时报错ValueError: Module parameters are different than optimizer Parameters

### ISSUE THREAD

**Issue by PaiStardian** [TsingZ0/PFL-Non-IID#131]
作者 你好，很感谢你上次回答我的问题
Algorithm: FedKD
Local batch size: 10
Local steps: 10
Local learing rate: 0.005
Local learing rate decay: False
Total number of clients: 3
Clients join in each round: 1.0
Clients randomly join: False
Client drop rate: 0.0
Client select regarding time: False
Running times: 1
Dataset: fmnist
Number of classes: 10
Backbone: cnn
Using device: cuda
Using DP: True
Sigma for DP: 0.7
Auto break: False
Global rounds: 50
Cuda device id: 0
DLG attack: False
Total number of new clients: 0
Fine tuning epoches on new clients: 0
报错 
Traceback (most recent call last):
  File "E:\yanjiusheng\PFL-Non-IID-KDsim\system\main.py", line 490, in <module>
    run(args)
  File "E:\yanjiusheng\PFL-Non-IID-KDsim\system\main.py", line 306, in run
    server.train()
  File "E:\yanjiusheng\PFL-Non-IID-KDsim\system\flcore\servers\serverkd.py", line 44, in train
    client.train()
  File "E:\yanjiusheng\PFL-Non-IID-KDsim\system\flcore\clients\clientkd.py", line 51, in train
    initialize_dp(self.global_model, self.optimizer, trainloader, self.dp_sigma)
  File "E:\yanjiusheng\PFL-Non-IID-KDsim\system\utils\privacy.py", line 8, in initialize_dp
    model, optimizer, data_loader = privacy_engine.make_private(
  File "E:\yanjiusheng\anaconda\envs\fl\lib\site-packages\opacus\privacy_engine.py", line 393, in make_private
    raise ValueError(
ValueError: Module parameters are different than optimizer Parameters
可以帮忙看一下 是我的参数出现了问题 还是什么原因 请您指正一下 感谢

**Comment by TsingZ0** [comment]
正如报错所示：ValueError: Module parameters are different than optimizer Parameters，你这里`initialize_dp`中的`self.global_model` 和 `self.optimizer`不匹配，应该是`self.global_model` 和 `self.optimizer_g`。
