### ISSUE TITLE
On the technical issue of t-SNE in GPFL

### ISSUE THREAD

**Issue by GerrysHazzah** [TsingZ0/PFL-Non-IID#146]
Thank you very much for your work and the code, which has given me a lot to think about and helped me in many ways. But as for the algorithm GPfl, I was reading your paper and noticed that you use t-SNE which is figure 2 when visualizing Learned Features, but I can't quite find the corresponding part in the code. I was wondering if you could give me some help in reproducing this part of the work as much as possible.

![Uploading figure2.png…]()

**Comment by TsingZ0** [comment]
We utilize the popular `sklearn.manifold.TSNE` tool for t-SNE visualization, which is based on the t-SNE [algorithm](https://www.jmlr.org/papers/volume9/vandermaaten08a/vandermaaten08a.pdf?fbcl) referred by our GPFL paper.

**Comment by GerrysHazzah** [comment]
Thank you for your answer, I will continue to learn about it next:）   
But I have another problem When I try to run GPfl the program works fine, but I find that when he saves the results he gets the following error:
Best accuracy.
0.2822085889570552

Average time cost per round.
1.4380106925964355

Average time cost: 4.22s.
Traceback (most recent call last):
  File "E:\pythonproject\PFL-Non-IID-master\system\main.py", line 519, in <module>
    run(args)
  File "E:\pythonproject\PFL-Non-IID-master\system\main.py", line 341, in run
    average_data(dataset=args.dataset, algorithm=args.algorithm, goal=args.goal, times=args.times)
  File "E:\pythonproject\PFL-Non-IID-master\system\utils\result_utils.py", line 7, in average_data
    test_acc = get_all_results_for_one_algo(algorithm, dataset, goal, times)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonproject\PFL-Non-IID-master\system\utils\result_utils.py", line 22, in get_all_results_for_one_algo
    test_acc.append(np.array(read_data_then_delete(file_name, delete=False)))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonproject\PFL-Non-IID-master\system\utils\result_utils.py", line 30, in read_data_then_delete
    with h5py.File(file_path, 'r') as hf:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Anacanda\envs\fl\Lib\site-packages\h5py\_hl\files.py", line 567, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Anacanda\envs\fl\Lib\site-packages\h5py\_hl\files.py", line 231, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 106, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to open file (unable to open file: name = '../results/har_GPFL_test_0.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

What's the reason for this?
