### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by GYJGYJGYJ** [TsingZ0/PFL-Non-IID#2]
When I use the "python main.py -data mnist -m cnn -algo FedAvg -gr 2500 -did 0 -go cnn"
It has an error as follows:
============= Running time: 0th =============
Creating server and clients ...
Traceback (most recent call last):
  File "main.py", line 183, in <module>
    run(goal=config.goal,
  File "main.py", line 61, in run
    server = FedAvg(device, dataset, algorithm, model, local_batch_size, local_learning_rate, global_rounds,
  File "/home/aa/federated-learning-benchmark/Personalized-federated-learning-simulation-platform-master/system/flcore/servers/serveravg.py", line 14, in __init__
    data = read_data(dataset)
  File "/home/aa/federated-learning-benchmark/Personalized-federated-learning-simulation-platform-master/system/utils/data_utils.py", line 80, in read_data
    train_file = os.listdir(train_data_dir)[0]
IndexError: list index out of range

This seems to be a data formatting error.

**Comment by TsingZ0** [comment]
Hi @GYJGYJGYJ, as mentioned in [README.md](https://github.com/TsingZ0/Personalized-federated-learning-simulation-platform#datasets), you may need to generate the dataset first.
