### ISSUE TITLE
Facing issues in using the code on google colab.

### ISSUE THREAD

**Issue by azalahmadkhan** [TsingZ0/PFL-Non-IID#21]
Hi, I was trying to use this library on google colab but am facing issues. Please add some instructions on how to use it on colab. Thanks.

On running this line, I am getting the below-mentioned error. Please guide me on how to remove this
```
!python main.py -data mnist -m cnn -algo FedAvg -gr 2500 -did 0 -go cnn
```
==================================================
Algorithm: FedAvg
Local batch size: 10
Local steps: 1
Local learing rate: 0.005
Total number of clients: 20
Clients join in each round: 1.0
Client drop rate: 0.0
Time select: False
Time threthold: 10000
Global rounds: 2500
Running times: 1
Dataset: mnist
Local model: cnn
Using device: cpu
==================================================

============= Running time: 0th =============
Creating server and clients ...
Traceback (most recent call last):
  File "main.py", line 307, in <module>
    run(args)
  File "main.py", line 106, in run
    server = FedAvg(args, i)
  File "/content/PFL-Non-IID/system/flcore/servers/serveravg.py", line 13, in __init__
    self.set_clients(args, clientAVG)
  File "/content/PFL-Non-IID/system/flcore/servers/serverbase.py", line 53, in set_clients
    train_data = read_client_data(self.dataset, i, is_train=True)
  File "/content/PFL-Non-IID/system/utils/data_utils.py", line 88, in read_client_data
    train_data = read_data(dataset, idx, is_train)
  File "/content/PFL-Non-IID/system/utils/data_utils.py", line 68, in read_data
    with open(train_file, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../dataset/mnist/train/0.npz'

**Comment by azalahmadkhan** [comment]
Also, is it possible to know the accuracies of each user?

**Comment by azalahmadkhan** [comment]
Found the solution -

These installations are required
```
!pip install ujson
!pip install opacus==0.15.0
!pip install calmsize
```
