### ISSUE TITLE
An error occurred when running generate_cifar10.py

### ISSUE THREAD

**Issue by llbbcc** [TsingZ0/PFL-Non-IID#3]
When I ran generate_cifar10.py, the following error appeared
Traceback (most recent call last):
  File "generate_cifar10_1.py", line 74, in <module>
    generate_cifar10(dir_path=dir_path, num_clients=num_clients, num_labels=num_labels, niid=niid, real=real)
  File "generate_cifar10_1.py", line 65, in generate_cifar10
    X, y, statistic = seperete_data(dataset, num_clients, num_labels, niid, real)
  File "/home/liubochao/code/PFL-Non-IID/PFL-Non-IID-c7dff7fb0575840727baa746eb08d9bd4c8ede22/dataset/utils/dataset_utils.py", line 42, in seperete_data
    dataset_content, dataset_label = data
ValueError: too many values to unpack (expected 2)

**Comment by llbbcc** [comment]
Thanks for your code! Only modified the data path of cifar10 in the running file during runtime

**Comment by TsingZ0** [comment]
Thank you for your attention! I have fixed this error in the new version.
https://github.com/TsingZ0/PFL-Non-IID/blob/9f3dd6c4ac5b7e8a15d07ef015eb8fd4f90beab3/dataset/generate_cifar10.py#L64-L65
