### ISSUE TITLE
many methods run wrong

### ISSUE THREAD

**Issue by FibonacciZ** [TsingZ0/PFL-Non-IID#56]
I try to run APPLE, FedRoD and Fedamp, different wrongs appear：

APPLE：Traceback (most recent call last):
  File "main.py", line 381, in <module>
    run(args)
  File "main.py", line 236, in run
    server.train()
  File "PFL-Non-IID/system/flcore/servers/serverapple.py", line 51, in train
    self.receive_models()
  File "PFL-Non-IID/system/flcore/servers/serverapple.py", line 78, in receive_models
    assert (len(self.selected_clients) > 0)
AssertionError

FedRoD：Traceback (most recent call last):
  File "main.py", line 381, in <module>
    run(args)
  File "main.py", line 236, in run
    server.train()
  File "PFL-Non-IID/system/flcore/servers/serverrod.py", line 30, in train
    self.evaluate()
  File "PFL-Non-IID/system/flcore/servers/serverbase.py", line 203, in evaluate
    stats = self.test_metrics()
  File "PFL-Non-IID/system/flcore/servers/serverbase.py", line 180, in test_metrics
    ct, ns, auc = c.test_metrics()
  File "PFL-Non-IID/system/flcore/clients/clientrod.py", line 96, in test_metrics
    lb = label_binarize(y.detach().cpu().numpy(), np.arange(nc))
TypeError: label_binarize() takes 1 positional argument but 2 were given

Fedamp：Traceback (most recent call last):
  File "main.py", line 381, in <module>
    run(args)
  File "main.py", line 236, in run
    server.train()
  File "PFL-Non-IID/system/flcore/servers/serveramp.py", line 43, in train
    self.receive_models()
  File "PFL-Non-IID/system/flcore/servers/serverbase.py", line 111, in receive_models
    client.send_time_cost['total_cost'] / client.send_time_cost['num_rounds']
ZeroDivisionError: float division by zero

Last，I dont know why the FedBN algorithm evaluate global model. FedBN  is a PFL method, I think FedBN should eveluate client models on each of dataset. In addition, FedBN do not avg the parameter of BatchnNormalization, so, the global model's accurancy should be worst. But in the test with this code, the global model's accurancy looks good.

**Comment by TsingZ0** [comment]
Thank you for reporting the errors. There may be some bugs when I updated the codes for some methods and python packages but forgot to update the corresponding codes of other methods. Please check the latest version :-).

For FedBN, since no BN parameter is uploaded to the server, there are no global model exists. All the BN parameters are personalized ones. Thus, `evaluate()` evaluates personalized models.

**Comment by TsingZ0** [comment]
> FedBN should eveluate client models on each of dataset.

Yes, this is how FedBN in this platform evaluated. 

In addition, please note that only if you use the model with BN layer(s) can FedAvg and FedBN be different.
