### ISSUE TITLE
No module named 'opacus.dp_model_inspector'

### ISSUE THREAD

**Issue by reidszu** [TsingZ0/PFL-Non-IID#7]
Hi, I have installed opacus but I still got this error when run the code:

(fl_torch) zrh@zrh-server:~/zhuyonghui/Project/FL/PFL-Non-IID-master/system$ python main.py -data mnist -m cnn -algo FedAvg -gr 2500 -did 0 -go cnn

Traceback (most recent call last):
  File "main.py", line 12, in <module>
    from flcore.servers.serveravg import FedAvg
  File "/home/zrh/zhuyonghui/Project/FL/PFL-Non-IID-master/system/flcore/servers/serveravg.py", line 1, in <module>
    from flcore.clients.clientavg import clientAVG
  File "/home/zrh/zhuyonghui/Project/FL/PFL-Non-IID-master/system/flcore/clients/clientavg.py", line 6, in <module>
    from utils.privacy import *
  File "/home/zrh/zhuyonghui/Project/FL/PFL-Non-IID-master/system/utils/privacy.py", line 2, in <module>
    from opacus.dp_model_inspector import DPModelInspector
ModuleNotFoundError: No module named 'opacus.dp_model_inspector'

Can you help me solve this problem? Thank you.

**Comment by TsingZ0** [comment]
dp_model_inspector() is not supported by the opacus v1.x. Here, the version of opacus is [v0.15.0](https://github.com/pytorch/opacus/releases/tag/v0.15.0). Please check `env_linux.yaml` for details.

**Comment by reidszu** [comment]
> dp_model_inspector() is not supported by the opacus v1.x. Here, the version of opacus is [v0.15.0](https://github.com/pytorch/opacus/releases/tag/v0.15.0). Please check `env_linux.yaml` for details.

It works now! Thank you very much!

**Comment by shooterkongque** [comment]
老哥你是怎么解决的？
